<?php
/**
 * @file
 * PDF tool module.
 */

/**
 * Implements hook_mediamosa_tool_can_analyse().
 */
function mediamosa_tool_pdf_mediamosa_tool_can_analyse($mime_type) {
  return mediamosa_tool_pdf::is_supported($mime_type);
}

/**
 * Implements hook_mediamosa_tool_analyse().
 *
 * Currently only implements number of pages.
 */
function mediamosa_tool_pdf_mediamosa_tool_analyse($mediafile_id) {

  $mediafile_path = mediamosa_storage::get_realpath_mediafile($mediafile_id);
  $execution_command = strtr('pdfinfo @mediafile', array('@mediafile' => $mediafile_path));
  mediamosa_watchdog::log_mediafile($mediafile_id, 'Start analyse: @command', array('@command' => $execution_command), NULL, WATCHDOG_NOTICE, 'tool pdf');
  $output_array = mediamosa_io::exec($execution_command);

  // Output of pdfinfo is in the form of "property : value"
  // for example "Pages:          3"
  foreach ($output_array as $value) {

    if (strpos($value, 'Pages:') !== FALSE) {
      list(, $pages) = explode(':', $value);
    }
    if (strpos($value, 'PDF version:') !== FALSE) {
      list(, $version) = explode(':', $value);
    }
  }

  $analyse = array();
  if (isset($pages)) {
    $analyse['pdf_pages'] = array('type' => 'INT', 'value' => trim($pages));
  }
  if (isset($version)) {
    $analyse['pdf_version'] = array('type' => 'CHAR', 'value' => trim($version));
  }

  return $analyse;
}

/**
 * Implements hook_mediamosa_tool_analyse_metadata().
 *
 * Used to be tool_analyse(). This will analyse the file for possible extra
 * Asset metadata.
 */
function mediamosa_tool_pdf_mediamosa_tool_analyse_metadata($job_ext) {
  $command_type = 'mediamosa_tool_pdf';
  $tool_id = mediamosa_tool_pdf::NAME;
  $execution_command = 'pdfinfo @mediafile_location';
  $separator = mediamosa_tool_pdf::MEDIAMOSA_TOOL_PDF_KEY_VALUE_SEPARATOR;
  mediamosa_tool_mapping::tool_analyse($job_ext, $command_type, $tool_id, $execution_command, $separator);
}

/**
 * Implements hook_mediamosa_tool_can_generate_still().
 */
function mediamosa_tool_pdf_mediamosa_tool_can_generate_still($mime_type) {
  return mediamosa_tool_pdf::is_supported($mime_type);
}

/**
 * Implements hook_mediamosa_tool_get_generate_still_exec().
 */
function mediamosa_tool_pdf_mediamosa_tool_get_generate_still_exec($job_info, $mediafile_id_source) {
  return mediamosa_tool_pdf::get_generate_still_exec($job_info, $mediafile_id_source);
}


/**
 * Implements hook_mediamosa_tool_info().
 */
function mediamosa_tool_pdf_mediamosa_tool_info() {
  return array(
    mediamosa_tool_pdf::NAME => array(
      'name' => t('PDF tool'),
      'description' => t('Tool for PDF files.'),
    ),
  );
}

/**
 * Generate information for the status page.
 */
function _mediamosa_tool_pdf_status_generate() {
  // For several topics we provide a link to webpages with configuration hints.
  $helper_links = array(
    'pdfinfo' => l(t('here'), 'http://mediamosa.org/trac/wiki/pdfinfo'),
  );

  $results = array();
  $exec_output = array();
  $found = mediamosa_io::command_installed('pdfinfo -v', $exec_output, array(0, 99));
  $status_line = $found ? _mediamosa_maintenance_status_search_in_array('version', $exec_output) : t('pdfinfo not found');
  $version = $found ? drupal_substr($status_line, drupal_strlen('pdfinfo version ')) : '';
  $pos = strpos($version, '.');
  if ($pos !== FALSE) {
    $version = drupal_substr($version, 0, $pos);
  }

  $results['app_pdfinfo'] = array(
    'title' => t('PDF tool: pdfinfo'),
    'value' => $status_line,
    'severity' => _mediamosa_maintenance_status_okerror($found && is_numeric($version) && $version >= mediamosa_tool_pdf::MEDIAMOSA_MAINTENANCE_STATUS_CONFIGURATION_PDFINFO_WARNING),
    'description' => $found ? '' : t('Install pdfinfo. You can find more information how to install pdfinfo !here', array('!here' => $helper_links['pdfinfo'])),
  );

  // Making the report.
  return array(
    'configuration' => array(
      'title' => t('PDF tool'),
      'results' => $results,
    ),
  );
}

/**
 * Implements hook_mediamosa_status_collect().
 */
function mediamosa_tool_pdf_mediamosa_status_collect($reset = FALSE) {
  $mediamosa_status_collect = array();
  if (!$reset) {
    $mediamosa_status_collect = variable_get('mediamosa_status_pdf_collect_' . mediamosa::get_server_id(), array());
  }

  if (empty($mediamosa_status_collect)) {
    $mediamosa_status_collect = array('time' => REQUEST_TIME, 'statuses' => _mediamosa_tool_pdf_status_generate());
    variable_set('mediamosa_status_pdf_collect_' . mediamosa::get_server_id(), $mediamosa_status_collect);
  }

  return $mediamosa_status_collect['statuses'];
}

/**
 * Implements hook mediafile_metadata_properties().
 */
function mediamosa_tool_pdf_mediafile_metadata_properties() {
  $properties = array(
    'pdf_pages' => array('title' => 'Number of pages'),
    'pdf_version' => array('title' => 'PDF version'),
  );
  return $properties;
}

/**
 * Implements hook mediafile_metadata_properties_alter().
 */
function mediamosa_tool_pdf_mediafile_metadata_properties_alter(&$properties) {
  $image_properties = mediamosa_tool_pdf_mediafile_metadata_properties();
  $properties = array_merge($properties, array_keys($image_properties));
}

/**
 * Implements hook_mediamosa_register_rest_call().
 */
function mediamosa_tool_pdf_mediamosa_register_rest_call() {
  $rest_calls = array();

  // Rest call to create a pdf job.
  $rest_calls['asset/$asset_id/pdf/create'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_asset_pdf_create',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_tool_pdf',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_3_6_0,
  );

  return $rest_calls;
}

/**
 * Implements hook_mediamosa_register_rest_call_doc().
 */
function mediamosa_tool_pdf_mediamosa_register_rest_call_doc() {
  $rest_calls = array();

  $rest_calls['asset/$asset_id/pdf/create'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::TITLE => 'Create PDF.',
    mediamosa_rest_call::DESCRIPTION => 'Start a create PDF-job from the asset_ids given and store this in asset_id. Only one mediafile per asset is taken, use the profile_id to determine which one (by default the original is taken). The PDF is created from a series of images and plain text files.',
    mediamosa_rest_call::EXAMPLE_REQUEST => '/asset/M9FyEFTVy0zFzpbOv7DaEH4U/pdf/create [POST]',
    mediamosa_rest_call::RESPONSE_FIELDS => array(
      'job_id' => 'Job id of the pdf job created.',
    ),
    mediamosa_rest_call::EXAMPLE_RESPONSE => '  <items>
    <item>
      <job_id>20621</job_id>
      <asset_id>M9FyEFTVy0zFzpbOv7DaEH4U</asset_id>
    </item>
  </items>',
  );
  return $rest_calls;
}
