<?php
/**
 * @file
 * PDF tool module.
 */

/**
 * Implements hook_mediamosa_tool_can_analyse().
 */
function mediamosa_tool_pdf_mediamosa_tool_can_analyse($mime_type) {
  return mediamosa_tool_pdf::is_supported($mime_type);
}

/**
 * Implements hook_mediamosa_tool_analyse().
 *
 * Currently only implements number of pages.
 */
function mediamosa_tool_pdf_mediamosa_tool_analyse($mediafile_id) {

  $mediafile_path = mediamosa_storage::get_realpath_mediafile($mediafile_id);
  $execution_command = strtr('pdfinfo @mediafile', array('@mediafile' => $mediafile_path));
  mediamosa_watchdog::log_mediafile($mediafile_id, 'Start analyse: @command', array('@command' => $execution_command), NULL, WATCHDOG_NOTICE, 'tool pdf');
  $output_array = mediamosa_io::exec($execution_command);

  // Output of pdfinfo is in the form of "property : value"
  // for example "Pages:          3"
  foreach ($output_array as $value) {
    if (strpos($value, 'Pages:') !== FALSE) {
      list(, $pages) = explode(':', $value);
    }
    if (strpos($value, 'PDF version:') !== FALSE) {
      list(, $version) = explode(':', $value);
    }
  }
  $analyse = array();
  $analyse['pages'] = array('type' => 'INT', 'value' => trim($pages));
  $analyse['PDF version'] = array('type' => 'CHAR', 'value' => trim($version));

  return $analyse;
}

/**
 * Implements hook_mediamosa_tool_analyse_metadata().
 *
 * Used to be tool_analyse(). This will analyse the file for possible extra
 * Asset metadata.
 */
function mediamosa_tool_pdf_mediamosa_tool_analyse_metadata($job_ext) {
  $command_type = 'mediamosa_tool_pdf';
  $tool_id = mediamosa_tool_pdf::NAME;
  $execution_command = 'pdfinfo @mediafile_location';
  $separator = mediamosa_tool_pdf::MEDIAMOSA_TOOL_PDF_KEY_VALUE_SEPARATOR;
  mediamosa_tool_mapping::tool_analyse($job_ext, $command_type, $tool_id, $execution_command, $separator);
}

/**
 * Implements hook_mediamosa_tool_info().
 */
function mediamosa_tool_pdf_mediamosa_tool_info() {
  return array(
    mediamosa_tool_pdf::NAME => array(
      'name' => t('PDF tool'),
      'description' => t('Tool for PDF files.'),
    ),
  );
}

/**
 * Generate information for the status page.
 */
function _mediamosa_tool_pdf_status_generate() {
  // For several topics we provide a link to webpages with configuration hints.
  $helper_links = array(
    'pdf2swf' => l(t('here'), 'http://mediamosa.org/trac/wiki/pdf2swf'),
    'pdfinfo' => l(t('here'), 'http://mediamosa.org/trac/wiki/pdfinfo'),
  );

  $results = array();

  $exec_output = array();
  $found = mediamosa_io::command_installed('pdf2swf -V', $exec_output);
  $status_line = $found ? _mediamosa_maintenance_status_search_in_array('part of', $exec_output) : t('pdf2swf not found');
  $version = $found ? drupal_substr($status_line, drupal_strlen('pdf2swf - part of swftools ')) : '';
  $pos = strpos($version, '.');
  if ($pos !== FALSE) {
    $version = drupal_substr($version, 0, $pos);
  }

  $results['app_pdf2swf'] = array(
    'title' => t('PDF tool: pdf2swf'),
    'value' => $status_line,
    'severity' => _mediamosa_maintenance_status_okerror($found && is_numeric($version) && $version >= mediamosa_tool_pdf::MEDIAMOSA_MAINTENANCE_STATUS_CONFIGURATION_PDF2SWF_WARNING),
    'description' => $found ? '' : t('Install pdf2swf. You can find more information how to install pdf2swf !here', array('!here' => $helper_links['pdf2swf'])),
  );

  $exec_output = array();
  $found = mediamosa_io::command_installed('pdfinfo -v', $exec_output, array(0, 99));
  $status_line = $found ? _mediamosa_maintenance_status_search_in_array('version', $exec_output) : t('pdfinfo not found');
  $version = $found ? drupal_substr($status_line, drupal_strlen('pdfinfo version ')) : '';
  $pos = strpos($version, '.');
  if ($pos !== FALSE) {
    $version = drupal_substr($version, 0, $pos);
  }

  $results['app_pdfinfo'] = array(
    'title' => t('PDF tool: pdfinfo'),
    'value' => $status_line,
    'severity' => _mediamosa_maintenance_status_okerror($found && is_numeric($version) && $version >= mediamosa_tool_pdf::MEDIAMOSA_MAINTENANCE_STATUS_CONFIGURATION_PDFINFO_WARNING),
    'description' => $found ? '' : t('Install pdfinfo. You can find more information how to install pdfinfo !here', array('!here' => $helper_links['pdfinfo'])),
  );

  // Making the report.
  return array(
    'configuration' => array(
      'title' => t('Image tool'),
      'results' => $results,
    ),
  );
}

/**
 * Implements hook_mediamosa_status_collect().
 */
function mediamosa_tool_pdf_mediamosa_status_collect($reset = FALSE) {
  $mediamosa_status_collect = array();
  if (!$reset) {
    $mediamosa_status_collect = variable_get('mediamosa_status_pdf_collect_' . mediamosa::get_server_id(), array());
  }

  if (empty($mediamosa_status_collect)) {
    $mediamosa_status_collect = array('time' => REQUEST_TIME, 'statuses' => _mediamosa_tool_pdf_status_generate());
    variable_set('mediamosa_status_pdf_collect_' . mediamosa::get_server_id(), $mediamosa_status_collect);
  }

  return $mediamosa_status_collect['statuses'];
}
