<?php
/**
 * @file
 * Module for remapping POST calls to GET.
 */

define('MEDIAMOSA_RESTCALL_POST2GET_PREFIX', 'post2get');

/**
 * Implements hook_mediamosa_register_rest_call_doc().
 */
function mediamosa_restcalls_post2get_mediamosa_register_rest_call_doc() {
  static $called = FALSE;

  // Make sure we don't loop.
  if ($called) {
    return array();
  }
  $called = TRUE;
  $rest_calls_doc = module_invoke_all('mediamosa_register_rest_call_doc');
  $called = FALSE;

  $remapped = array();
  foreach ($rest_calls_doc as $uri => $rest_call_doc) {
    foreach ($rest_call_doc as $method => $rest_call_doc_2) {
      if ($method != 'POST') {
        continue;
      }

      $remapped[MEDIAMOSA_RESTCALL_POST2GET_PREFIX . '/' . $uri]['GET'] = $rest_call_doc_2;
    }
  }

  return $remapped;
}

/**
 * Implements hook_mediamosa_register_rest_call().
 */
function mediamosa_restcalls_post2get_mediamosa_register_rest_call() {
  static $called = FALSE;

  // Make sure we don't loop.
  if ($called) {
    return array();
  }
  $called = TRUE;
  $rest_calls = module_invoke_all('mediamosa_register_rest_call');
  $called = FALSE;

  $remapped = array();
  foreach ($rest_calls as $uri => $rest_call) {
    foreach ($rest_call as $method => $rest_call_2) {
      if ($method != 'POST') {
        continue;
      }

      $remapped[MEDIAMOSA_RESTCALL_POST2GET_PREFIX . '/' . $uri]['GET'] = $rest_call_2;
    }
  }

  return $remapped;
}
