<?php
/**
 * @file
 * The database class of the asset module.
 */

class mediamosa_asset_delete_db {
  // ------------------------------------------------------------------- Consts.
  // Table name;
  const TABLE_NAME = 'mediamosa_asset_delete';

  // Database fields;
  const ID = 'asset_id';
  const APP_ID = 'app_id';
  const VIDEOTIMESTAMPMODIFIED = 'videotimestampmodified';
  const COLL_ID = 'coll_id';
}
