<?php
/**
 * @file
 * Proxy module.
 */

/**
 * Implements hook_mediamosa_settings_collect().
 */
function mediamosa_configuration_proxy_mediamosa_configuration_collect() {
  $form['settings_proxy'] = array(
    '#type' => 'fieldset',
    '#title' => t('Proxy settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['settings_proxy']['mediamosa_curlproxy_http'] = array(
    '#type' => 'textfield',
    '#title' => t('Proxy Url'),
    '#description' => t('The proxy url is used when HTTP requests can not be reached directly because of firewalls or other reasons. These requests are f.e. requests to signal upload completion or when a job has been finished. Leave empty if servers can access outside webservers without problems.'),
    '#required' => FALSE,
    '#default_value' => variable_get('mediamosa_curlproxy_http', ''),
  );

  return $form;
}
