<?php
// $Id$

/**
 * MediaMosa is Open Source Software to build a Full Featured, Webservice
 * Oriented Media Management and Distribution platform (http://mediamosa.org)
 *
 * Copyright (C) 2011 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

/**
 * @file
 * FTP user module.
 */

/**
 * Implements hook_mediamosa_register_rest_call().
 */
function mediamosa_ftp_user_mediamosa_register_rest_call() {

  $rest_calls = array();

  $rest_calls['ftp'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_ftp_user_list',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_ftp_user',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $rest_calls['ftp/list'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_ftp_user_list',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_DEPRECATED,
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_ftp_user',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $rest_calls['ftp/$user/create'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_ftp_user_create',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_DEPRECATED,
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_ftp_user',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $rest_calls['ftp/create'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_ftp_user_create',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_ftp_user',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $rest_calls['ftp/$user/delete'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_ftp_user_delete',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_ftp_user',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $rest_calls['ftp/$user/update'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_ftp_user_update',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_ftp_user',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $rest_calls['ftp/$user'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_ftp_user_update',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_ftp_user',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $rest_calls['ftp/$user'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_ftp_user_get',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_ftp_user',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $rest_calls['ftp/$user/change_password'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_ftp_user_update_password',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_DEPRECATED,
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_ftp_user',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

    $rest_calls['ftp/$user/change_status'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_ftp_user_update_status',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_DEPRECATED,
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_ftp_user',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  return $rest_calls;
}

/**
 * Implements hook_mediamosa_register_rest_call_doc().
 */
function mediamosa_ftp_user_mediamosa_register_rest_call_doc() {

  $rest_calls = array();

  $rest_calls['ftp/list'][mediamosa_rest_call::METHOD_GET] = // deprecated
  $rest_calls['ftp'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::TITLE => 'Get the listing of the FTP users.',
    mediamosa_rest_call::EXAMPLE_REQUEST => '/ftp ',
    mediamosa_rest_call::DESCRIPTION => 'mediamosa supports upload files through ftp. There are a number of rest calls available to the ega builder to maintain a set of ftp users. The features needs a configured ftp server, with mod_sql. Ask on the forum for more information if needed.

The /ftp [GET] restcall gives a list of all ftp users of the ega.',
    mediamosa_rest_call::EXAMPLE_RESPONSE => '<items>
  <item>
    <userid>testuser</userid>
    <active>true</active>
    <modified>2009-04-04 00:34:03</modified>
  </item>
</items>',
    mediamosa_rest_call::RESPONSE_FIELDS => array('userid' => 'ftp loginname'),
  );

  $rest_calls['ftp/$user/create'][mediamosa_rest_call::METHOD_POST] = // deprecated
  $rest_calls['ftp/create'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::TITLE => 'Create a FTP user.',
    mediamosa_rest_call::EXAMPLE_REQUEST => '/ftp/create [POST] username=foofoo&password=foofoofoo ',
    mediamosa_rest_call::DESCRIPTION => 'Create a FTP user. A 3-digit text is added to the ftp username, to ensure unique ftpusers. The password must be at least 8 characters.',
    mediamosa_rest_call::EXAMPLE_RESPONSE => FALSE,
    mediamosa_rest_call::RESPONSE_FIELDS => array(),
  );

  $rest_calls['ftp/$user/delete'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::TITLE => 'Delete a FTP user.',
    mediamosa_rest_call::EXAMPLE_REQUEST => '/ftp/foofoo/delete ',
    mediamosa_rest_call::DESCRIPTION => 'Deletes a ftp-user. The home directory is not cleaned.',
    mediamosa_rest_call::EXAMPLE_RESPONSE => FALSE,
    mediamosa_rest_call::RESPONSE_FIELDS => array(),
  );

  $rest_calls['ftp/$user/update'][mediamosa_rest_call::METHOD_POST] = // deprecated
  $rest_calls['ftp/$user'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::TITLE => 'Update a FTP user.',
    mediamosa_rest_call::EXAMPLE_REQUEST => '/ftp/foofoo [POST] active=false&password=barbar',
    mediamosa_rest_call::DESCRIPTION => 'Updates the ftp-user. A user can be disabled (with active), and the password can be changed.',
    mediamosa_rest_call::EXAMPLE_RESPONSE => FALSE,
    mediamosa_rest_call::RESPONSE_FIELDS => array(),
  );

  $rest_calls['ftp/$user'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::TITLE => 'Get a FTP user.',
    mediamosa_rest_call::EXAMPLE_REQUEST => '/ftp/foofoo [GET] ',
    mediamosa_rest_call::DESCRIPTION => 'Get all the available details of a ftp-user.',
    mediamosa_rest_call::EXAMPLE_RESPONSE => '<items>
  <item>
    <userid>testuser</userid>
    <active>true</active>
    <modified>2009-04-04 00:34:03</modified>
  </item>
</items>',
    mediamosa_rest_call::RESPONSE_FIELDS => array(),
  );

  $rest_calls['ftp/$user/change_password'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::TITLE => 'This REST call is deprecated, use ftp/$user [POST] instead.',
    mediamosa_rest_call::EXAMPLE_REQUEST => '',
    mediamosa_rest_call::DESCRIPTION => '',
    mediamosa_rest_call::EXAMPLE_RESPONSE => '',
    mediamosa_rest_call::RESPONSE_FIELDS => array(),
  );

  $rest_calls['ftp/$user/change_status'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::TITLE => 'This REST call is deprecated, use ftp/$user [POST] instead..',
    mediamosa_rest_call::EXAMPLE_REQUEST => '',
    mediamosa_rest_call::DESCRIPTION => '',
    mediamosa_rest_call::EXAMPLE_RESPONSE => '',
    mediamosa_rest_call::RESPONSE_FIELDS => array(),
  );

  return $rest_calls;
}
