<?php
/**
 * @file
 * FFmpeg tool module.
 */

/**
 * Implements hook_permission().
 */
function mediamosa_tool_ffmpeg_permission() {
  return array(
    'access mediamosa tool ffmpeg' =>  array(
      'title' => t('Access MediaMosa Tool module for FFmpeg toolset'),
      'description' => t('Enables the user to use the FFmpeg toolset.'),
    ),
  );
}

/**
 * Implements hook_mediamosa_tool_info().
 *
 * @return array
 *  An array filled with information about the tool.
 */
function mediamosa_tool_ffmpeg_mediamosa_tool_info() {
  return array(mediamosa_tool_ffmpeg::NAME => array(
    'name' => t('ffmpeg'),
    'description' => t('The ffmpeg tool for transcoding video files.'),
  ));
}

/**
 * Implements hook_mediamosa_tool_mapping().
 *
 * @return The mapping array.
 */
function mediamosa_tool_ffmpeg_mediamosa_tool_mapping() {
  return mediamosa_tool_params::get_by_tool(mediamosa_tool_ffmpeg::NAME);
}

/**
 * Implements hook_mediamosa_tool_param_checking().
 *
 * @return array
 *  The mapping array.
 */
function mediamosa_tool_ffmpeg_mediamosa_tool_param_checking($nice_parameter, $value) {
  mediamosa_tool_params::check_mapping(mediamosa_tool_ffmpeg::NAME, $nice_parameter, $value);
}
