<?php
// $Id$

/**
 * MediaMosa is Open Source Software to build a Full Featured, Webservice
 * Oriented Media Management and Distribution platform (http://mediamosa.org)
 *
 * Copyright (C) 2011 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

/**
 * @file
 * The status commponent module.
 */

/**
 * Constants.
 */

/**
 * Warning level for available in Mb.
 */
define('MEDIAMOSA_MAINTENANCE_STATUS_COMPONENT_SPACE_WARNING', 100);

/**
 * When CRON is considered not being updated on time.
 */
define('MEDIAMOSA_MAINTENANCE_STATUS_COMPONENT_CRON_TIMEOUT', 180);

/**
 * When simpletest is taking to much space and needs to be cleared.
 */
define('MEDIAMOSA_MAINTENANCE_STATUS_COMPONENT_DU_SIMPLETEST_WARNING', 1024 * 1024 * 512);

/**
 * Generate the information of the status page.
 */
function mediamosa_maintenance_status_component_generate() {
  $results = array();

  // Get the mount point. The mount point always ends with DIRECTORY_SEPARATOR.
  $mount_point = mediamosa_configuration_storage::mount_point_get();

  // ------------------------------------------------------- SANNAS mount point.
  $results['mount_set'] = array(
    'title' => t('SANNAS'),
    'value' => t('Mount set'),
    'severity' => _mediamosa_maintenance_status_okerror(!empty($mount_point)),
  );

  $results['mount_exists'] = array(
    'title' => t('SANNAS'),
    'value' => t('Mount exists'),
    'severity' => _mediamosa_maintenance_status_okerror(mediamosa_io::is_dir($mount_point)),
  );

  // --------------------------------------------------- SANNAS media/.htaccess.
  $path = mediamosa_configuration_storage::media_get_path();
  $found = mediamosa_io::file_exists($path . '.htaccess');

  // Create when missing.
  if (!$found && is_writable($mount_point)) {
    // Make the [mount_point]/media directory.
    mediamosa_io::mkdir($path);
    mediamosa_io::mkdir($path . 'ticket' . DIRECTORY_SEPARATOR);
    $found = mediamosa_configuration_storage::file_create_htaccess($path, mediamosa_configuration_storage::media_get_htaccess_contents());
  }

  $htaccess = explode("\n", trim(file_get_contents($path . '.htaccess')));
  foreach ($htaccess as $key => $line) {
    $htaccess[$key] = trim($line, "\n\r\t ");
  }
  $htaccess_org = explode("\n", trim(mediamosa_configuration_storage::media_get_htaccess_contents()));
  foreach ($htaccess_org as $key => $line) {
    $htaccess_org[$key] = trim($line, "\n\r\t ");
  }
  $contents = $found ? implode('', $htaccess) == implode('', $htaccess_org) : FALSE;
  $results['mount_media_htaccess'] = array(
    'title' => t('SANNAS .htaccess media'),
    'value' => $found && $contents ? t('Found & contents ok') : ($found && !$contents ? t('Found, but incorrect contents') : t('Not found, unable to create')),
    'severity' => !$contents && $found ? _mediamosa_maintenance_status_okwarning(FALSE) : _mediamosa_maintenance_status_okerror($found && $contents),
  );
  if (!$found || !$contents) {
    $variables = array('%directory' => $path, '@path' => $path . '.htaccess', '!htaccess' => nl2br(check_plain(mediamosa_configuration_storage::media_get_htaccess_contents())));
    $results['mount_media_htaccess']['description'] = t("Warning: Couldn't find .htaccess file in location @path (or with correct contents).<br />Please create a .htaccess file in your %directory directory which contains the following lines: <br /><code>!htaccess</code>", $variables);
  }

  // --------------------------------------------------- SANNAS Structure check.
  $checks = array(
    'is_structured' => array(),
    'is_writeable' => array(),
  );

  $dirs = array('data', 'data/stills', 'data/transcode', 'links', 'download_links', 'media', 'media/ticket', 'ftp');
  foreach ($dirs as $dir) {
    $checks = _mediamosa_maintenance_status_component_directory($mount_point . $dir, $checks);
  }

  $maps = array(
    '1', '2', '3', '4', '5', '6', '7', '8', '9',
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
  );
  foreach ($maps as $map) {
    _mediamosa_maintenance_status_component_directory($mount_point . 'data' . DIRECTORY_SEPARATOR . $map, $checks);
    _mediamosa_maintenance_status_component_directory($mount_point . 'data' . DIRECTORY_SEPARATOR . 'stills' . DIRECTORY_SEPARATOR . $map, $checks);
  }

  $results['mount_structure'] = array(
    'title' => t('SANNAS stucture'),
    'value' => empty($checks['is_structured']) ? t('Good') : t('Failures'),
    'severity' => _mediamosa_maintenance_status_okerror(empty($checks['is_structured'])),
  );
  if (!empty($checks['is_structured'])) {
    $results['mount_structure']['description'] = '<pre>' . implode("\n", $checks['is_structured']) . '</pre>';
  }

  $results['mount_writeable'] = array(
    'title' => t('SANNAS writable'),
    'value' => empty($checks['is_structured']) ? t('Writable') : t('Failures'),
    'severity' => _mediamosa_maintenance_status_okerror(empty($checks['is_writeable'])),
  );
  if (!empty($checks['is_writeable'])) {
    $results['mount_writeable']['description'] = '<pre>' . implode("\n", $checks['is_writeable']) . '</pre>';
  }

  $filename = $mount_point . '/data/transcode/test_' . mt_rand(0, 9999) . '.txt';
  $content = mt_rand(0, 9999);
  $read_content = '';

  $handle = fopen($filename, 'w');
  if ($handle) {
    fwrite($handle, $content);
    fclose($handle);
    $handle = fopen($filename, 'rb');
    if ($handle) {
      $read_content = fread($handle, filesize($filename));
      fclose($handle);
    }

    unlink($filename);
  }

  // Note; you can not rename the key 'mount_rea_write' (!).
  // This name can not be changed because its used in the status REST call.
  $results['mount_rea_write'] = array(
    'title' => t('SANNAS read and write'),
    'value' => t('Readable & writable'),
    'severity' => _mediamosa_maintenance_status_okerror($content == $read_content),
  );

  $available_bytes = mediamosa_io::disk_free_space($mount_point);
  $available_mb = floor($available_bytes / (1024 * 1024));
  $total_bytes = mediamosa_io::disk_total_space($mount_point);
  $results['mount_disk_free'] = array(
    'title' => t('SANNAS current diskspace'),
    'value' => t('@available free of total @total (@used used)', array('@available' => format_size($available_bytes), '@total' => format_size($total_bytes), '@used' => format_size($total_bytes - $available_bytes))),
    'severity' => $available_mb <= MEDIAMOSA_MAINTENANCE_STATUS_COMPONENT_SPACE_WARNING ? MEDIAMOSA_MAINTENANCE_STATUS_RESULT_WARNING : ($available_bytes <= 0 ? MEDIAMOSA_MAINTENANCE_STATUS_RESULT_ERROR : MEDIAMOSA_MAINTENANCE_STATUS_RESULT_OK),
  );

  if (!empty($mount_point) && is_dir($mount_point)) {
    $du_simpletest = mediamosa_io::disk_usage_recursive(mediamosa_configuration_storage::mount_point_get(TRUE));
    $results['du_simpletest'] = array(
      'title' => t('Simpletest diskusage'),
      'value' => format_size($du_simpletest),
      'severity' => $du_simpletest > MEDIAMOSA_MAINTENANCE_STATUS_COMPONENT_DU_SIMPLETEST_WARNING ? MEDIAMOSA_MAINTENANCE_STATUS_RESULT_WARNING : MEDIAMOSA_MAINTENANCE_STATUS_RESULT_OK,
      'description' => $du_simpletest > MEDIAMOSA_MAINTENANCE_STATUS_COMPONENT_DU_SIMPLETEST_WARNING ? t("The diskspace used by simpletest is only used temporary. Crashed tests will not remove their files automaticly. An administrator needs to clean up directory '@simpletest_dir'", array('@simpletest_dir' => mediamosa_configuration_storage::mount_point_get(TRUE))) : '',
    );
  }

  return array(
    'components' => array(
      'title' => t('Components'),
      'results' => $results,
    ),
  );
}

/**
 * Directory check helper.
 *
 * @param $directory string
 * @param $checks['is_structured'] string
 * @param $checks['is_writeable'] string
 */
function _mediamosa_maintenance_status_component_directory($directory, $checks) {
  if (!mediamosa_io::is_dir($directory)) {
    $checks['is_structured'][] = $directory;
  }
  if (!is_writable($directory)) {
    $checks['is_writeable'][] = $directory;
  }

  return $checks;
}

/**
 * Implements hook_mediamosa_status_collect().
 *
 * @param boolean $reset
 *  Reset the data, regenerate.
 *
 * @return array
 *   All the statuses in an array
 */
function mediamosa_maintenance_status_component_mediamosa_status_collect($reset = FALSE) {
  $mediamosa_status_component = array();
  if (!$reset) {
    $mediamosa_status_component = variable_get('mediamosa_status_component_' . mediamosa::get_server_id(), array());
  }

  if (empty($mediamosa_status_component)) {
    $mediamosa_status_component = array('time' => REQUEST_TIME, 'statuses' => mediamosa_maintenance_status_component_generate());
    variable_set('mediamosa_status_component_' . mediamosa::get_server_id(), $mediamosa_status_component);
  }

  return $mediamosa_status_component['statuses'];
}

/**
 * Implements hook_mediamosa_status_collect_realtime().
 *
 * Collect the information always, no caching. Only for front status page.
 */
function mediamosa_maintenance_status_component_mediamosa_status_collect_realtime() {

  // -------------------------------------------------- Check Drupal status page
  $results['update_db'] = array(
    'title' => t('Drupal status page'),
    'severity' => MEDIAMOSA_MAINTENANCE_STATUS_RESULT_OK,
    'value' => t('Good'),
  );

  // Include code for system_status.
  module_load_include('inc', 'system', 'system.admin');

  if (system_status(TRUE) && user_access('administer site configuration')) {
    $results['update_db']['severity'] = MEDIAMOSA_MAINTENANCE_STATUS_RESULT_ERROR;
    $results['update_db']['value'] = t('Error on Drupal status page');
    $results['update_db']['description'] = t('One or more problems were detected with your Drupal installation. Check the <a href="@status">status report</a> for more information.', array('@status' => url('admin/reports/status')));
  }

  // --------------------------------------------------------------- CRON check.
  $cron_last = variable_get('cron_last');
  if (!is_numeric($cron_last)) {
    $cron_last = variable_get('install_time', 0);
  }

  $cron_running = (REQUEST_TIME - $cron_last < 180);
  $results['cron'] = array(
    'title' => t('Cron maintenance tasks'),
    'value' => $cron_running ? t('Last run %last_run ago', array('%last_run' => format_interval(REQUEST_TIME - $cron_last))) : t('Did not run for %run_for', array('%run_for' => format_interval(REQUEST_TIME - $cron_last))),
    'severity' => _mediamosa_maintenance_status_okerror($cron_running),
  );

  // Only when failed and we have administer rights.
  if (!$cron_running && user_access('administer site configuration')) {
    global $base_url;
    $description[] = t('You can <a href="@cron">run cron manually</a>.', array('@cron' => url('admin/reports/status/run-cron')));
    $description[] = t('To run cron from outside the site, go to <a href="!cron">!cron</a>', array('!cron' => url($base_url . '/cron.php', array('external' => TRUE, 'query' => array('cron_key' => variable_get('cron_key', 'drupal'))))));
    $results['cron']['description'] = implode(' ', $description);
  }

  return array(
    'components' => array(
      'title' => t('Components'),
      'results' => $results,
    ),
  );
}
