<?php
/**
 * @file
 * MediaMosa support for Metadata type Dublin Core.
 */

/**
 * Implements hook_mediamosa_metadata_info().
 */
function mediamosa_metadata_dc_mediamosa_metadata_info() {
  return array(
    mediamosa_metadata_dc::METADATA_PROPERTY_GROUP_NAME => array(
      'title' => t('Dublin Core'),
      'description' => t('MediaMosa support for the metadata format Dublin Core. See !link for more information.', array('!link' => url('http://dublincore.org/'))),
      'context' => 'dc',
      'context_full' => 'dublin_core',
    ),
  );
}
