<?php
/**
 * @file
 * MediaMosa support for Metadata type Content Zoek Profiel (Content Search
 * Profile).
 */

/**
 * Implements hook_mediamosa_metadata_info().
 */
function mediamosa_metadata_czp_mediamosa_metadata_info() {
  return array(
    mediamosa_metadata_czp::METADATA_PROPERTY_GROUP_NAME => array(
      'title' => t('Content Search Profile'),
      'description' => t('MediaMosa support for the metadata (Dutch) format Content Zoek Profiel (Content Search Profile)'),
      'context' => 'czp',
      'context_full' => 'czp',
    ),
  );
}
