<?php
/**
 * @file
 * Audio tool module.
 */

/**
 * Implements hook_permission().
 */
function mediamosa_tool_libreoffice_permission() {
  return array(
    'access mediamosa tool audio' => array(
      'title' => t('Access MediaMosa Tool module for LibreOffice toolset'),
      'description' => t('Enables the user to use the LibreOffice toolset.'),
    ),
  );
}

/**
 * Implements hook_mediamosa_tool_info().
 */
function mediamosa_tool_libreoffice_mediamosa_tool_info() {
  return array(
    mediamosa_tool_libreoffice::NAME => array(
      'name' => t('LibreOffice'),
      'description' => t('The tool for converting office files.'),
    )
  );
}

/**
 * Implements hook_mediamosa_tool_can_analyse().
 */
function mediamosa_tool_libreoffice_mediamosa_tool_can_analyse($mime_type) {
  return mediamosa_tool_libreoffice::is_supported($mime_type);
}

/**
 * Implements hook_mediamosa_tool_analyse().
 */
function mediamosa_tool_libreoffice_mediamosa_tool_analyse($mediafile_id) {

  // Analyse of audio files is done by the ffmpeg toolset.
  return mediamosa_tool_ffmpeg_mediamosa_tool_analyse($mediafile_id);
}

/**
 * Implements hook_mediamosa_tool_can_generate_still().
 */
function mediamosa_tool_libreoffice_mediamosa_tool_can_generate_still($mime_type) {
  return FALSE;
}

/**
 * Implements hook_mediamosa_tool_get_generate_still_exec().
 */
function mediamosa_tool_libreoffice_mediamosa_tool_get_generate_still_exec($job_info, $mediafile_id_source) {
  return FALSE;
}

/**
 * Implements hook_mediamosa_tool_mapping().
 */
function mediamosa_tool_libreoffice_mediamosa_tool_mapping() {
  return mediamosa_tool_params::get_by_tool(mediamosa_tool_libreoffice::NAME);
}

/**
 * Implements hook_mediamosa_tool_param_checking().
 */
function mediamosa_tool_libreoffice_mediamosa_tool_param_checking($nice_parameter, $value) {

  mediamosa_tool_params::check_mapping(mediamosa_tool_libreoffice::NAME, $nice_parameter, $value);
}

/**
 * Generate information for the status page.
 */
function _mediamosa_tool_libreoffice_status_generate() {
  // For several topics we provide a link to webpages with configuration hints.
  $helper_links = array(
    'libreoffice' => l(t('here'), 'http://libreoffice.org'),
  );

  $results = array();
  $exec_output = array();
  $found = mediamosa_io::command_installed('libreoffice --version', $exec_output, array(
    0,
    99
  ));
  $status_line = $found ? _mediamosa_maintenance_status_search_in_array('Build', $exec_output) : t('libreoffice not found');
  $version = $found ? drupal_substr($status_line, drupal_strlen('LibreOffice ')) : '';
  $pos = strpos($version, '.');
  if ($pos !== FALSE) {
    $version = drupal_substr($version, 0, $pos);
  }

  $results['app_libreofficeinfo'] = array(
    'title' => t('LibreOffice'),
    'value' => $status_line,
    'severity' => _mediamosa_maintenance_status_okerror($found && is_numeric($version) && $version >= mediamosa_tool_libreoffice::MEDIAMOSA_MAINTENANCE_STATUS_CONFIGURATION_LIBREOFFICE_WARNING),
    'description' => $found ? '' : t('Install libreoffice. You can find more information how to install libreoffice !here', array('!here' => $helper_links['libreoffice'])),
  );

  // Making the report.
  return array(
    'configuration' => array(
      'title' => t('LibreOffice Tool'),
      'results' => $results,
    ),
  );
}
