<?php
/**
 * @file
 * Image tool module.
 */

/**
 * Implements hook_mediamosa_tool_info().
 *
 * Get information about the tool.
 */
function mediamosa_tool_image_mediamosa_tool_info() {
  return array(
    mediamosa_tool_image::NAME => array(
      'name' => t('ImageMagick'),
      'description' => t('Image files like JPG, PNG, TIFF.'),
    ));
}

/**
 * Implements hook_mediamosa_tool_can_analyse().
 */
function mediamosa_tool_image_mediamosa_tool_can_analyse($mime_type) {
  return mediamosa_tool_image::is_supported($mime_type);
}

/**
 * Implements hook_mediamosa_tool_analyse().
 *
 * Currently only implements width/height.
 */
function mediamosa_tool_image_mediamosa_tool_analyse($mediafile_id) {

  $mediafile_path = mediamosa_storage::get_realpath_mediafile($mediafile_id);
  $execution_command = strtr('exiv2 @mediafile', array('@mediafile' => $mediafile_path));
  mediamosa_watchdog::log_mediafile($mediafile_id, 'Start analyse: @command', array('@command' => $execution_command), NULL, WATCHDOG_NOTICE, 'tool image');
  $output_array = mediamosa_io::exec($execution_command);

  // Output of exiv2 is in the form of "property : value"
  // for example "Image size      : 3414 x 5090"
  foreach ($output_array as $value) {
    if (strpos($value, 'Image size') !== FALSE) {
      list($property, $size) = explode(':', $value);
      list($width, $height) = explode('x', $size);
    }
  }
  $analyse = array();
  $analyse['width'] = array('type' => 'INT', 'value' => trim($width));
  $analyse['height'] = array('type' => 'INT', 'value' => trim($height));

  return $analyse;
}

/**
 * Implements hook_mediamosa_tool_analyse_metadata().
 *
 * Used to be tool_analyse(). This will analyse the file for possible extra
 * Asset metadata.
 */
function mediamosa_tool_image_mediamosa_tool_analyse_metadata($job_ext) {
  $command_type = 'mediamosa_tool_image';
  $tool_id = mediamosa_tool_image::NAME;
  $execution_command = 'exiv2 @mediafile_location';
  $separator = mediamosa_tool_image::MEDIAMOSA_TOOL_IMAGE_KEY_VALUE_SEPARATOR;
  mediamosa_tool_mapping::tool_analyse($job_ext, $command_type, $tool_id, $execution_command, $separator);
}

/**
 * Implements hook_mediamosa_tool_store_technical_metadata().
 */
function mediamosa_tool_image_mediamosa_tool_store_technical_metadata($technical_metadata_mapping) {
  $new_mapping = array();
  foreach ($technical_metadata_mapping as $key => $value) {
    switch ($key) {
      case 'image size':
        $metadata_value = str_replace(' ', '', $value);
        $matches = array();
        if (preg_match('/(?P<width>\d+)+x(?P<height>\d+)$/', $metadata_value, $matches)) {
          $new_mapping['width'][mediamosa_asset_mediafile_metadata_property_db::TYPE_INT] = $matches['width'];
          $new_mapping['height'][mediamosa_asset_mediafile_metadata_property_db::TYPE_INT] = $matches['height'];
        }
        break;
    }
  }
  return $new_mapping;
}

/**
 * Implements hook_mediamosa_tool_can_generate_still().
 */
function mediamosa_tool_image_mediamosa_tool_can_generate_still($mime_type) {
  return mediamosa_tool_image::is_supported($mime_type);
}

/**
 * Implements hook_mediamosa_tool_get_generate_still_exec().
 *
 * @deprecated: Although new hook, we will replace this with a other hook in
 *              v3.5 called 'hook_mediamosa_tool_generate_still' which will
 *              generate still without returning a exec string.
 */
function mediamosa_tool_image_mediamosa_tool_get_generate_still_exec($jobserver_job_id, $mediafile_id_source) {
  return mediamosa_tool_image::get_generate_still_exec($jobserver_job_id, $mediafile_id_source);
}

/**
 * Generate information for the status page.
 */
function _mediamosa_tool_image_status_generate() {
  // For several topics we provide a link to webpages with configuration hints.
  $helper_links = array(
    'imagemagic' => l('here', 'http://www.imagemagick.org/'),
    'exiv2' => l('here', 'http://www.exiv2.org/'),
  );

  $results = array();

  $exec_output = array();
  $found = mediamosa_io::command_installed('convert -version', $exec_output);
  $status_line = $found ? _mediamosa_maintenance_status_search_in_array('Version', $exec_output) : t('ImageMagic not found');
  $version = $found ? drupal_substr($status_line, drupal_strlen('Version: ImageMagic ')) : '';
  $pos = strpos($version, '.');
  if ($pos !== FALSE) {
    $version = drupal_substr($version, 0, $pos);
  }

  $results['app_imagemagic'] = array(
    'title' => t('Image tool: ImageMagic'),
    'value' => $status_line,
    'severity' => _mediamosa_maintenance_status_okerror($found && is_numeric($version) && $version >= mediamosa_tool_image::MEDIAMOSA_MAINTENANCE_STATUS_CONFIGURATION_IMAGEMAGIC_WARNING),
    'description' => $found ? '' : t('Install ImageMagic. You can find more information how to install ImageMagic !here', array('!here' => $helper_links['imagemagic'])),
  );


  $exec_output = array();
  $found = mediamosa_io::command_installed('exiv2 -h', $exec_output);
  $status_line = $found ? _mediamosa_maintenance_status_search_in_array('Manipulate', $exec_output) : t('Exiv2 not found');

  $results['app_exiv2'] = array(
    'title' => t('Image tool: Exiv2'),
    'value' => $status_line,
    'severity' => _mediamosa_maintenance_status_okerror($found),
    'description' => $found ? '' : t('Install Exiv2. You can find more information how to install Exiv2 !here', array('!here' => $helper_links['exiv2'])),
  );

  // Making the report.
  return array(
    'configuration' => array(
      'title' => t('Image tool'),
      'results' => $results,
    ),
  );
}

/**
 * Implements hook_mediamosa_status_collect().
 *
 * @param reset boolean
 *
 * @return array
 *   All the statuses in an array
 */
function mediamosa_tool_image_mediamosa_status_collect($reset = FALSE) {
  $mediamosa_status_collect = array();
  if (!$reset) {
    $mediamosa_status_collect = variable_get('mediamosa_status_image_collect_' . mediamosa::get_server_id(), array());
  }

  if (empty($mediamosa_status_collect)) {
    $mediamosa_status_collect = array('time' => REQUEST_TIME, 'statuses' => _mediamosa_tool_image_status_generate());
    variable_set('mediamosa_status_image_collect_' . mediamosa::get_server_id(), $mediamosa_status_collect);
  }

  return $mediamosa_status_collect['statuses'];
}
